---
- name: "updating apt"
  become: yes
  apt:
    update_cache: yes
- name: "upgrading apt packages"
  become: true
  apt:
    upgrade: "yes"
- name: "installing dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
- name: "installing n"
  become: yes
  npm:
    name: n
    global: yes
    production: yes
- name: "installing nodejs 13.8.0"
  become: yes
  shell: n 13.8.0
- name: "installing pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present